name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}  # Use GitHub username for login
          password: ${{ secrets.GHCR_TOKEN }}  # Use the secret token to authenticate

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/my-app:${{ github.sha }} .
          
      # Step 4: Push the Docker image to GitHub Container Registry
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/my-app:${{ github.sha }}

      # Optional: Step 5: Tag the Docker image with 'latest' tag
      - name: Tag Docker image with 'latest'
        run: |
          docker tag ghcr.io/${{ github.repository }}/my-app:${{ github.sha }} ghcr.io/${{ github.repository }}/my-app:latest

      - name: Push 'latest' tag to GHCR
        run: |
          docker push ghcr.io/${{ github.repository }}/my-app:latest
